"""Agrega tanque_id a Bomba y elimina estacion_id

Revision ID: c636285e98fa
Revises: 
Create Date: 2025-06-23 16:47:23.361448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c636285e98fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bombas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tanque_id', sa.Integer(), nullable=False))
        batch_op.alter_column('numero_bomba',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_bombas_tanque_id', 'tanques', ['tanque_id'], ['id'])
        batch_op.drop_column('estacion_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bombas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estacion_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_bombas_tanque_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_bombas_estacion_id', 'estaciones', ['estacion_id'], ['id'])
        batch_op.alter_column('numero_bomba',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('tanque_id')

    # ### end Alembic commands ###
